[project]
name = "fustor-agent-sdk"
dynamic = ["version"]
description = "SDK for Fustor Agent service"
dependencies = [ "fustor-core", "fustor-registry-client",]

[build-system]
requires = [ "setuptools>=61.0", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "dirty-tag"

["project.urls"]
Homepage = "https://github.com/excelwang/fustor/tree/master/packages/fustor_agent_sdk"
"Bug Tracker" = "https://github.com/excelwang/fustor/issues"

[tool.setuptools.packages.find]
where = [ "src",]
