[project]
name = "fustor-agent-sdk"
version = "0.1.0"
description = "SDK for Fustor Agent service"
dependencies = [
    "fustor-core",
    "fustor-registry-client",
]

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
