sources:
  nfs-source:
    driver: fs
    uri: "/data"
senders:
  fusion-main:
    driver: fusion
    uri: "http://fusion:18888"
    credential: { key: "agent-2-push-key" }
pipes:
  sync-job: { source: nfs-source, sender: fusion-main }
