[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project]
name = "fustor_pusher_fusion"
version = "0.1.0"
description = "Fustor agent pusher driver for the Fustor Fusion service."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [ "Programming Language :: Python :: 3", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent",]
dependencies = [ "fustor-core", "fustor-fusion-sdk",]
[[project.authors]]
name = "Huajin Wang"
email = "wanghuajin999@163.com"

[project.urls]
Homepage = "https://github.com/excelwang/fustor/tree/master/packages/pusher_fusion"
"Bug Tracker" = "https://github.com/excelwang/fustor/issues"

[project.entry-points."fustor_agent.drivers.pushers"]
fusion = "fustor_pusher_fusion:FusionDriver"

[tool.setuptools.packages.find]
where = [ "src",]
