[project]
name = "fustor-source-fs"
version = "0.1.0"
description = "Fustor Agent FS Source Driver"
dependencies = [
    "fustor-core",
    "fustor-event-model",
    "watchdog",
]

[project.entry-points."fustor_agent.drivers.sources"]
fs = "fustor_source_fs:FSDriver"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"