[project]
name = "fustor-source-fs"
version = "0.1.0"
description = "Fustor Agent FS Source Driver"
dependencies = [ "fustor-core", "fustor-event-model", "watchdog",]

[build-system]
requires = [ "setuptools>=61.0",]
build-backend = "setuptools.build_meta"

["project.urls"]
Homepage = "https://github.com/excelwang/fustor/tree/master/packages/source_fs"
"Bug Tracker" = "https://github.com/excelwang/fustor/issues"

[project.entry-points."fustor_agent.drivers.sources"]
fs = "fustor_source_fs:FSDriver"
