[project]
name = "fustor-source-fs"
version = "0.1.0"
description = "A filesystem source for Fustor Agent"
authors = [
    {name = "Huajin Wang", email = "wanghuajin999@163.com"},
]
license = {text = "MIT"}
requires-python = ">=3.12"
dependencies = [
    "fustor-core"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "ruff>=0.1.0",
    "mypy>=1.0.0",
    "pytest-asyncio>=0.23.0",
    "watchdog>=4.0.0"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points."fustor_agent.drivers.sources"]
fs = "fustor_source_fs:FSDriver"
