agent_id: "agent-2"
sources:
  fs-source:
    driver: fs
    uri: "/data"
senders:
  fusion:
    driver: fusion
    uri: "http://fusion:18888"
    credential: { key: "key-agent-2" }
pipes:
  sync-pipe:
    source: fs-source
    sender: fusion
