[project]
name = "fustor-view-fs"
dynamic = ["version"]
description = "Fustor FS Consistent View Driver"
license = "MIT"
dependencies = [
    "fustor-core",
    "fustor-schema-fs",
    "fastapi",
    "pydantic",
]


[project.optional-dependencies]
test = [
    "pytest>=8.0",
    "pytest-asyncio>=1.0",
]


[build-system]
requires = ["setuptools>=61.0", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
root = "../.."
version_scheme = "post-release"
local_scheme = "dirty-tag"

["project.urls"]
Homepage = "https://github.com/excelwang/fustor/tree/master/packages/view-fs"
"Bug Tracker" = "https://github.com/excelwang/fustor/issues"

[project.entry-points."fustor.view_drivers"]
fs = "fustor_view_fs:FSViewDriver"

[project.entry-points."fustor.view_api"]
fs = "fustor_view_fs:create_fs_router"
