[project]
name = "fustor-fusion-sdk"
version = "0.1.0"
description = "SDK for Fustor Fusion service"
dependencies = [ "fustor-common", "fustor-registry-client",]

[build-system]
requires = [ "setuptools>=61.0",]
build-backend = "setuptools.build_meta"

["project.urls"]
Homepage = "https://github.com/excelwang/fustor/tree/master/packages/fustor_fusion_sdk"
"Bug Tracker" = "https://github.com/excelwang/fustor/issues"

[tool.setuptools.packages.find]
where = [ "src",]
