[project]
name = "fustor-common"
version = "0.1.0"
description = "Common utilities and models for Fustor services"
requires-python = ">=3.12"
dependencies = [
    "colorlog>=6.10.1",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.3.4",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
