[project]
name = "fustor-core"
version = "0.1.0"
description = "Core components for Fustor services and plugins"
requires-python = ">=3.11"
dependencies = [ "pydantic>=2.11.7",]
[[project.authors]]
name = "Huajin Wang"
email = "wanghuajin999@163.com"

[build-system]
requires = [ "setuptools>=61.0",]
build-backend = "setuptools.build_meta"

["project.urls"]
Homepage = "https://github.com/excelwang/fustor/tree/master/packages/core"
"Bug Tracker" = "https://github.com/excelwang/fustor/issues"

license = "MIT"

[project.optional-dependencies]
dev = [ "pytest>=8.0.0", "ruff>=0.1.0", "mypy>=1.0.0", "pytest-asyncio>=0.23.0",]

[tool.setuptools.packages.find]
where = [ "src",]
