agent_id: "agent-3"

sources:
  fs-source:
    driver: fs
    uri: "/data"

senders:
  fusion:
    driver: fusion
    uri: "http://fusion:18888"
    credential: { key: "key-agent-3" }

pipes:
  sync-pipe:
    source: fs-source
    sender: fusion
