[project]
name = "fustor-pusher-echo"
version = "0.1.0"
description = "An echo pusher for Fustor Agent"
requires-python = ">=3.11"
dependencies = [ "fustor-core",]
[[project.authors]]
name = "Huajin Wang"
email = "wanghuajin999@163.com"

[build-system]
requires = [ "setuptools>=61.0",]
build-backend = "setuptools.build_meta"

["project.urls"]
Homepage = "https://github.com/excelwang/fustor/tree/master/packages/pusher_echo"
"Bug Tracker" = "https://github.com/excelwang/fustor/issues"

license = "MIT"

[project.entry-points."fustor_agent.drivers.pushers"]
echo = "fustor_pusher_echo:EchoDriver"

[tool.setuptools.packages.find]
where = [ "src",]
