[project]
name = "fustor-source-fs"
version = "0.8.13"
description = "Fustor Agent FS Source Driver"
license = "MIT"
dependencies = ["fustor-core", "fustor-schema-fs", "watchdog"]

[build-system]
requires = [ "setuptools>=61.0" ]
build-backend = "setuptools.build_meta"



["project.urls"]
Homepage = "https://github.com/excelwang/fustor/tree/master/extensions/source-fs"
"Bug Tracker" = "https://github.com/excelwang/fustor/issues"

[project.entry-points."fustor_agent.drivers.sources"]
fs = "fustor_source_fs:FSDriver"
