[project]
name = "fustor-pusher-openapi"
version = "0.1.0"
description = "An OpenAPI pusher for Fustor Agent"
authors = [
    {name = "Huajin Wang", email = "wanghuajin999@163.com"},
]
license = {text = "MIT"}
requires-python = ">=3.12"
dependencies = [
    "fustor-core"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points."fustor_agent.drivers.pushers"]
openapi = "fustor_pusher_openapi:OpenApiDriver"
